DROP DATABASE IF EXISTS restaurante;

CREATE DATABASE restaurante;

USE restaurante;

CREATE TABLE restaurante (
    CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CORREO VARCHAR(50) NOT NULL,
    CLAVE BINARY(60) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    CP VARCHAR(5) NOT NULL,
    PAIS VARCHAR(50) NOT NULL
);

CREATE TABLE pedido (
    CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL,
    ENVIADO BOOLEAN NOT NULL,
    CODIGO_RESTAURANTE INT NOT NULL REFERENCES restaurante(CODIGO) ON DELETE CASCADE
);

CREATE TABLE producto (
    CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PESO DECIMAL(5,2) NOT NULL,
    STOCK INT NOT NULL,
    COD_CAT INT NOT NULL REFERENCES categoria(CODIGO) ON DELETE CASCADE
);

CREATE TABLE ped_prod (
    CODIGO_PEDIDO INT NOT NULL REFERENCES pedido(CODIGO) ON DELETE CASCADE,
    CODIGO_PRODUCTO INT NOT NULL REFERENCES producto(CODIGO) ON DELETE CASCADE,
    CANTIDAD INT NOT NULL,
    PRIMARY KEY (CODIGO_PEDIDO, CODIGO_PRODUCTO)
);

CREATE TABLE categoria (
    CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL
);